# Generated by Django 3.1.2 on 2020-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_cost',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_cost',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
